### PR TITLE
Added "carthage" package manager support

### PR DESCRIPTION
**Pull request by dodikk**
* Added a dynamic framework target
* Added a shared scheme
* Added a static framework target

### CODE REVIEW

**Comment by dodikk** [comment]
@ColinEberhardt is this repo abandoned? Should I send a patch anywhere else so that Carthage package manager gets adopted?

**Comment by ColinEberhardt** [comment]
No, it is not abandoned!

**Comment by ColinEberhardt** [comment]
Sorry for not looking at this PR sooner, I have quite a few projects on the go, so things occasionally fall off my radar! I'll check it tonight.

Many thanks for contributing.

**Comment by ColinEberhardt** [comment]
Merged, many thanks. I renamed the new method to `linq_selectAndStopOnNil`, I think it is a better description of what the method does, and follows the naming convention. I hope that doesn't cause you any problems?

**Pull request merged**
